### ISSUE TITLE
Doesn't work in SublimeText 3

### ISSUE THREAD

**Issue by simonschaufi** [colinta/SublimeChangeQuotes#11]
Take this php snippet as example:

```php
<?php
echo "<input type=\"hidden\">";
```

I would expect something like that afterwards:

```php
<?php
echo '<input type="hidden">';
```

But instead i get an error: Could not find matching quote (None)

**Comment by simonschaufi** [comment]
I think i figured out how this plugin actually works. Instead of selecting the whole line, I just need to select the quote that i want to be changed. Well, for me it would make sense if i select the whole line and then the plugin figures out the correct quoting and changes it.

**Comment by colinta** [comment]
You should be able to place the cursor inside the quotes; no selection support that I know of actually.

**Comment by simonschaufi** [comment]
ok, if i do that, then some more complex lines break:

```php
echo '<input type='hidden' name='demo' value="'.htmlspecialchars('demo').'">';
```

When i place the cursor above "input", then i get this:
```php
echo "<input type="hidden' name='demo' value="'.htmlspecialchars('demo').'">';
```

**Comment by colinta** [comment]
`echo '<input type='` closes that string, so this actually looks right to me.

**Comment by simonschaufi** [comment]
ups, wrong demo code :D

**Comment by colinta** [comment]
It's working fine for me on your examples:

```php
<?php
echo "<|input type=\"hidden\">";
   //  ^ cursor (anywhere inside the string)
```
`ctrl+"` (`ctrl+shift+'`)

```php
<?php
echo '<input type="hidden">';
  // ^ here       and here ^
```

**Comment by simonschaufi** [comment]
There is just no documentation how to use it and for me it is intuitive to select the whole line but then it doesn't work.

**Comment by colinta** [comment]
Sorry dude, I wrote it to work how I wanted it to work.  I think it works *better* this way - saves you from having to select the line, and works with multiple cursors.

If you want to update the README, though, to clarify its usage, I'd love that!

**Comment by colinta** [comment]
And of course, I'll fix any bugs you find.  Just let me know! :smiley:
