### ISSUE TITLE
Feature Request: Change quotes for entire document

### ISSUE THREAD

**Issue by doque** [colinta/SublimeChangeQuotes#14]
This would be a great improvement over `cmd+d`ing the entire document or using search/replace.

**Comment by colinta** [comment]
This is not a feature I have a need for, but I would welcome a PR that adds this!

**Comment by pepkin88** [comment]
Possible solution (keystrokes on Windows):
- select a quote
- Alt-F3 (selects all occurrences in the document)
- left arrow
- Ctrl-'
