### ISSUE TITLE
don't work just with empty quote

### ISSUE THREAD

**Issue by MxJ24** [colinta/SublimeChangeQuotes#15]
There is a bug, if you put the cursor just before the right quote it don't work or just the your cursor inside the empty quote like this '' or ""

**Comment by colinta** [comment]
What language grammar are you using?  This plugin uses sublime text’s syntax detection to find the current selection that is marked as a “string” according to the language.  Ruby, for instance, works great, but it doesn’t work well in Markdown.

**Comment by MxJ24** [comment]
I just test it in plain text, because I want to format some "JSON" literal output by python.
for example:
{
    u'name': u''
}
but this is invalid JSON , so I want to remove the u prefix and change the single quote to double quote and then format it.
Finally I found a way to format it within PyCharm.
Thanks anyway.

**Comment by colinta** [comment]
Gotcha. Yeah that's not supported. Glad you found a solution! Can you close since this is no longer an issue?
