### ISSUE TITLE
Convert to backticks

### ISSUE THREAD

**Issue by smanolloff** [colinta/SublimeChangeQuotes#20]
Hi, wonderful plugin there, I have been using it for years now without any complaints.

With ES6 introducing [template strings](https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/template_strings), it would be super nice if the plugin alternates between `'`, `"` and `` ` `` within a `source.js` context.

**Comment by elado** [comment]
:+1:

**Comment by colinta** [comment]
I love the idea!  Let's see a pull request!  I never write javascript, so I'm not going to do this.

**Comment by colinta** [comment]
@elado +1 comments are not productive on github.  Deleting.

**Comment by wesbos** [comment]
This would be super handy :)

**Comment by aug-riedinger** [comment]
Glad to read string interpolation is coming. Did not know about that!

Though for now, I'd like to get back to the previous behavior: even in JS files, `'` convert to `"` and reciprocally.

What options are necessary to achieve that? Tried:

```
{
  "lists": {
    "source.js": {
      "quotes": [["\"", "'"]]
    }
  }
}
```
but it doesn't seem to work.

**Comment by smanolloff** [comment]
Hi @aug-riedinger 

first, please check if you are on the latest version ("Package Control: Upgrade Package") -- a minor fix adding a menu entry was released earlier today.

Then, please try replacing your user settings (`Package Settings -> ChangeQuotes -> Settings (User)`) with:
```json
{
  "debug": false,
  "lists": {
    "default": {
      "quotes": [["'", "\""]]
    },
    "source.python": {
      "prefixes": [
        "r", "u", "ur", "R", "U", "UR", "Ur", "uR",
        "b", "B", "br", "Br", "bR", "BR"
      ],
      "quotes": [["'", "\""], ["'''", "\"\"\""]]
    }
  }
}
```

If it does not work, please inspect the console log (via `ctrl`+`~`) and let us know.

**Comment by colinta** [comment]
@smanolloff Thanks for the ongoing support.  I've added you as a contributor, no pressure to join, but I think you understand this plugin *as much if not more than I do* :grin:!

**Comment by smanolloff** [comment]
A pleasure for me! Thx @colinta :beer:

**Comment by aug-riedinger** [comment]
Thanks @smanolloff for your support. It worked really well.

Shouldn't this be the default options though? So that behavior is backward compatible.

**Comment by smanolloff** [comment]
You have a point there.
@colinta, what you think? I personally agree with @aug-riedinger (my initial idea was to be backwards-compatible, but I guess I just wanted those backticks too much and pushed them upstream as the new defaults ;) )

**Comment by colinta** [comment]
I'm torn, because I would love to encourage ES6 features as much as possible, but I think you're right, we should target "old javascript" as the default.  I wonder what we should do to let people know that backticks-support is there?

**Comment by aug-riedinger** [comment]
Here's my opinion:

First, people *will* use string interpolation, as this is highly useful. :smile: But very few people are allowed to write ES6 JS :( (either needs babel preprocessor, or writing very modern JS like react-native). I think babel created a file extension `es6` to distinguish those from classical JS.

Besides, I found weird to have a loop of three. As far as I'm concerned, I'd expect having different actions for looping between `'` and `"` (eg. *ChangeQuotes*) and `'` and ``` eg. *ChangeQuotesAlt*.

Anyways, hard to anticipate the need as long as I don't have it, but not being backward compatible may result many frustration among users...

**Comment by colinta** [comment]
Yeah I still agree with having the default be to alternate `' / "`, but I disagree about having different actions, only because I don't want another command and key combination.  I'm already using this feature daily, and having it *cycle* instead of alternate has been really handy.

`.es6` is not widely used in the React world, and besides we don't examine the file extension, we use the language grammar (this allows ChangeQuotes to work inside markdown code blocks, so I'm not going to budge on this).

1. Quick fix: updated the README, and changed the default: 2ee3c66

**Comment by smanolloff** [comment]
\o/ and thx for updating the README, totally forgot about this part.
