### ISSUE TITLE
Supporting LiveScript's `\string` syntax

### ISSUE THREAD

**Issue by colinta** [colinta/SublimeChangeQuotes#23]
I was looking into this today, and there are a few curveballs to go over. CC @smanolloff @pepkin88 

First, I'm going to assume that the language grammar is `source.livescript`.

Right now this plugin is very much tied to the idea that a string starts and ends with the same character - the regex matches, building the `start/end/inner` regions, they all assume this.  So we'll have to build something very *different* to handle `\strings`, since they only have a start delimiter, and no formal "closing" character(s).

I think the easiest way out of this pickle is to have "custom" searches.  These would bypass the current regex building / replacing, and could still be customized in Settings for other languages.  Something like this:

```json
{
  "lists": {
    "..."
    "source.livescript": {
      "custom": [
        "string_begins_with", ["\\"]
      ]
    }
```

The name `string_begins_with` would be a method on `ChangeQuotes`, and it would take over after `expand_regions`

```python
region = self.expand_region(sel_region)
if not region:
    return

if self.custom:
    fn_name = self.custom[0]
    fn_args = self.custom[1]
    try:
        fn = getattr(self, fn_name)
    except AttributeError:
        return
    fn(*fn_args)
    return
```

**Comment by smanolloff** [comment]
Hi @colinta 

very nice you took some time to look into it! I personally am overwhelmed by unrelated stuff and did not pay much attention on the recent events around here.

I will try to see if I can follow up on your suggested approach! I was actually thinking of maybe allowing to specify a start AND and end quote for for each list... but it gets rather complex, e.g. we would have
```
"default": {
 "quotes": [ [ ["\"", "\""], ["'", "'"] ] ]
}
```
...which, to be honest, looks awful :D Maybe accept both a lists and strings, the former indicating different start/end quotes and the latter -- same (like it is now). This would limit the usage of array-in-array-in-array to just the (rather rare) cases like the one we have with livescript, yet provide extensive flexibility with all sorts of quotes (it could even be used for brackets... e.g. {}, (), <>, [], ...)

**Comment by pepkin88** [comment]
Thank you for your involvement in the issue.

The thing is that the backslash strings have this special behavior and also few quirks, so I think creating a completely special case for that and not trying to generalize it would be a preferable way. I also can't think of any other language with strings with similar characteristics.

Let me explain the specificity of such strings in comparison to the standard quote strings in LiveScript or other languages:
- not every string can be expressed as a backslash string
	- but if it can, it might not be lossless convertible, e.g. `"prop": 1` cannot convert directly to `\prop: 1`, because then the `:` becomes a part of the string
- they start with `\` and end with `)`, `]`, `}`, `,`, `;`, a white space or EOF
	- unlike quote strings, you cannot escape the closing character in order to include it into the string
- you cannot express an empty string with it
	- that means `\)`, `\]` etc. compile to `')'`, `']'` respectively. That's the only way for `)`, `]` etc. to be in a backslash string
- you cannot include a space or a new line into the backslash string (you can include escaped characters though, such as `\n`)
	- a backslash before a white space causes the white space to be ignored by the compiler; it doesn't have anything to do with strings here
- although inside of the string `\` escapes the following character, there can be standalone `\` at the end of the string, e.g. `\foo\` -> `'foo\\'`

I managed to cover most of these rules in the [previous version of ChangeQuotes](https://github.com/colinta/SublimeChangeQuotes/commit/cbda2e73df86554e211e42e80e1d4a7372996976) (I missed the `\prop: 1` and `\)` like cases).

My approach was to enable conversion wherever it's possible, and where it isn't, skip the backslash string phase. So in the essence, when you trigger the change 6 times, you should always be back to where you started (or to an equivalent, e.g. `\foo\` -> `\foo\\`).

But I also thought of a slight extension, which would enable conversion of `"prop": 1` to `\prop : 1`, I'm calling it a "pushing behavior" (I'm using it locally, very useful, for me at least). Such option would be under a setting, disabled by default (sometimes putting a space changes semantics). What do you think?

**Comment by colinta** [comment]
@pepkin88 I think I've got this pretty close, want to give it a try?

https://github.com/colinta/SublimeChangeQuotes/tree/livescript

**Comment by YayConnolly** [comment]
Chiming in to say this would be awesome for things like `:symbols` or even heredocs in e.g. ruby. Defining both delimiters (start and end) would add a lot of power!

**Comment by pepkin88** [comment]
As of merging #27, the feature has been added, so I'll close this.
