### ISSUE TITLE
Change quote stuck if space in quoted string

### ISSUE THREAD

**Issue by LeonardoGentile** [colinta/SublimeChangeQuotes#28]
Hello, thank you very much for this plugin 👍 

I've found a corner case: if inside a json file I try to change the quotes of an attribute values and if there is a space in that string then the plugin get stuck (won't cycle again) after switching from double to single quotes.

```
{
    "key1": "avalue",
    "key2": "a value"
}
```
So in this case the plugin will work for key1 but not for key2. It will switch from doudle quotes to single quotes and then hitting the shortcut again will not produce any result anymore.

**Comment by pepkin88** [comment]
Double quotes are the only quotes legal in JSON (unless inside of a string). The plugin makes use of the editor's parser to detect, if there is a string and how long it is.

The solution for this would be disallowing changing quotes in the JSON files. Creating our own parser would require big changes in the code and it isn't that much needed anyway.

Another solution would be to change the syntax to JavaScript for the time of editing.

**Comment by smanolloff** [comment]
I agree with @pepkin88. Once you switch to single quote, it stops being a `string`. The reason why it works when there is no space is in the plugin's logic. We should not fix this logic as this is anyway not a valid string in the first place. This can (and should) be addressed in the plugin's default configuration:
```json
{
  "lists": {
    "source.json": {
      "quotes": [["\""]]
    },
    ...
  }
}
```
No quote other than `"` should be allowed in a json context. You can add the above block manually to Package Settings -> Change Quotes -> Settings - User.

**Comment by colinta** [comment]
Agreed: adding @smanolloff's settings change in #29, and this is a "should not" fix issue.

**Comment by colinta** [comment]
Thank you for reporting, it, though!  Important that the JSON behavior is well defined.
