### ISSUE TITLE
Allow replacement of non-equal typographic quote characters

### ISSUE THREAD

**Issue by kleinfreund** [colinta/SublimeChangeQuotes#31]
It would be great if one could also toggle through quote characters where opening and closing quote do not match each other as in:

```
“…”
„…“
«…»
『…』
```

I often write regular text in Sublime and use typographically-correct quotation characters, apostrophes, etc. Currently, I have snippets in place that trigger on `doublequotes` (`dou` is really sufficient) and suggest what you see in the code block above and put the selection on the ellipsis. Toggling through predefined quote sets would be way easier.

I would try to implement this myself and submit a pull request but I’m not quite sure where to start with this.

**Comment by pepkin88** [comment]
I'm not sure if the plugin is suited for such task and vice versa. I mean, the plugin resolves around programming languages and their quotes, it even uses the editor's parser to detect, where are strings.

You might already have looked up this in the code, there are two modes of quote recognition: inside of a string and outside of a string. If such typographic quotes would be inside of a string, they would be skipped until the end of the string, where the "real" quotes would be taken. So not much to do there.

For the second mode, looking outside of the string, you can dabble in the `expand_to_match` method. It will be useful for comment sections or non-programming file types, such as plain text or markdown (probably).

So if that's what are you shooting for, feel free to experiment. But I'm still not sure if this feature belongs to this package, maybe it is. And as always I'm interested in opinion of other contributors.

**Comment by kleinfreund** [comment]
I see. I did not think about this package as being programming-specific. In that case, you’re probably right in that my suggestion not being in scope of the package.

Replacing typographic quotation marks in plain text (so not in strings of a programming language) should be sufficient in almost all cases.
