### ISSUE TITLE
KeyError: 'lists' while applying the command

### ISSUE THREAD

**Issue by evandrocoan** [colinta/SublimeChangeQuotes#32]
I created this file within the `LaTeX` syntax:
```latex
    1. Add new lines after "{" and before "}"
    2. Add new lines before "{"
    3. Remove empty lines
    4. Add comment lines before function
    5. Add new lines after ";"
    6. Add new lines after "}"
    7. Remove new lines
    8. Reduce whitespace
    9. Put the code again in the input box above after submit
```

And called the command `Ctrl+Shift+P -> Change Quotes`, but the plugin did nothing and I got on the console this:
```
Traceback (most recent call last):
  File "D:\User\Dropbox\Applications\SoftwareVersioning\SublimeText\sublime_plugin.py", line 574, in run_
    return self.run(edit)
  File "D:\User\Dropbox\Applications\SoftwareVersioning\SublimeText\Data\Packages\SublimeChangeQuotes\change_quotes.py", line 98, in run
    self.run_each(edit, region, **kwargs)
  File "D:\User\Dropbox\Applications\SoftwareVersioning\SublimeText\Data\Packages\SublimeChangeQuotes\change_quotes.py", line 103, in run_each
    self.apply_scope(cursor)
  File "D:\User\Dropbox\Applications\SoftwareVersioning\SublimeText\Data\Packages\SublimeChangeQuotes\change_quotes.py", line 168, in apply_scope
    self.quote_lists = config["lists"]["default"]["quotes"]
KeyError: 'lists'
```

Also would be possible to do the conversion from normal quotes `"quote-me"` to latex quotes ``quote-me'' with this package or there are there some other package which does it?

**Comment by smanolloff** [comment]
Would you please paste your plugin settings? (Package Settings > ChangeQuotes > Settings - User)?

**Comment by evandrocoan** [comment]
there is not settings there, they are empty.

**Comment by evandrocoan** [comment]
Stranger, the default settings are also empty. 
May it is related to the Sublime Text version. 
I am using build 3114.

To install the plugin I just opened the `Packages` folder and typed `git clone repo...`

**Comment by smanolloff** [comment]
It must be related to the way you installed the package (i.e. not via package control).
When you open the default settings, you said it opens an empty file -- check the file path, maybe it is not `<PACKAGES>/ChangeQuotes/ChangeQuotes.sublime-settings`.
I would generally advise you to install packages via package control.
If you don't want to do that for some reason, open the package's user settings and paste the contents of [this file](https://github.com/colinta/SublimeChangeQuotes/blob/master/ChangeQuotes.sublime-settings) there, restart and then try again.

**Comment by evandrocoan** [comment]
Thanks, thought, I tried to install it via package control, but I could not find. May be I should look better. Then I just cloned this repository. 

I just deleted the package and installed it by Package Control. When I did so, it give this error on console:
```
reloading plugin ChangeQuotes.change_quotes
Traceback (most recent call last):
  File "D:\User\Dropbox\Applications\SoftwareVersioning\SublimeText\sublime_plugin.py", line 120, in reload_plugin
    m.plugin_loaded()
  File "change_quotes in D:\User\Dropbox\Applications\SoftwareVersioning\SublimeText\Data\Installed Packages\ChangeQuotes.sublime-package", line 79, in plugin_loaded
  File "change_quotes in D:\User\Dropbox\Applications\SoftwareVersioning\SublimeText\Data\Installed Packages\ChangeQuotes.sublime-package", line 61, in build_config
  File "change_quotes in D:\User\Dropbox\Applications\SoftwareVersioning\SublimeText\Data\Installed Packages\ChangeQuotes.sublime-package", line 31, in reorder_list_settings
AttributeError: 'NoneType' object has no attribute 'items'
``` 
But now I opened the default settings, and this was there:
```json
{
  "debug": false,
  "lists": {
    "default": {
      "quotes": [["'", "\""]]
    },
    // "source.js": {
    //   "quotes": [["'", "\"", "`"]]
    // },
    "source.json": {
      "quotes": [["\""]]
    },
    "source.coffee": {
      "quotes": [["'", "\""], ["'''", "\"\"\""]]
    },
    "source.litcoffee": {
      "quotes": [["'", "\""], ["'''", "\"\"\""]]
    },
    "source.python": {
      "prefixes": [
        "r", "u", "ur", "R", "U", "UR", "Ur", "uR",
        "b", "B", "br", "Br", "bR", "BR"
      ],
      "quotes": [["'", "\""], ["'''", "\"\"\""]]
    }
  }
}
```

Then now I copied it these to the user settings file, and restarted Sublime Text, and tried the command on the initial file again. 

Now it does not throw any errors. The file just stayed as it was:
```
    1. Add new lines after "{" and before "}"
    2. Add new lines before "{"
    3. Remove empty lines
    4. Add comment lines before function
    5. Add new lines after ";"
    6. Add new lines after "}"
    7. Remove new lines
    8. Reduce whitespace
    9. Put the code again in the input box above after submit
```
I think it is because there are not latex quotes on it.

**Comment by smanolloff** [comment]
Strange, if the command is present in the palette, then it should be working.
Your cursor must be _between_ the quotes when you invoke the command -- can you double check.

**Comment by evandrocoan** [comment]
Haha, I cannot believe, it worked. It does converted from double quote to single quote.
I thought I need to select all the text within the quotes. 

Can it be performed on the selected text?

I also tried it with a latex double quote, as:
```latex
    5. Add new lines after ``;''
```
But it did not converted to:
```latex
    5. Add new lines after `;'
```

**Comment by smanolloff** [comment]
It can be performed on the selected text, but the selection must not include the quotes themselves.

Regarding the latex double quote, this is a feature not yet implemented in the plugin (different start and end quote characters). It currently works only if the start/end quotes are the same (e.g. for python `'''some string'''` converts to `"""some string"""`). So, ultimately, you can't use this plugin for latex quotes, sorry.

**Comment by colinta** [comment]
@smanolloff Big thanks for helping Evandro resolve this, it's awesome that on Sunday when I got around to checking on this it was already resolved (as much as it could be - sorry we don't have support for all these quoting systems).

@evandrocoan Looks like this is resolved as much as it can be at the moment, I'll close this issue.

**Comment by evandrocoan** [comment]
@colinta, could those features:

1. Be implemented on this package
1. Or would be better writing a new package
1. Or already there is some other package out there doing it?

**Comment by colinta** [comment]
1. Yes!  A while back someone wanted support for livescript's `\string` syntax, and they added it using a `custom` handler.  See the default settings and search the package source code for `livescript`.
2. That's your call, I think writing packages is straightforward and fun, I won't tell you not to!
3. I have no idea.
