### ISSUE TITLE
Feature request for Smart Curly Quotes

### ISSUE THREAD

**Issue by TeffenEllis** [colinta/SublimeChangeQuotes#34]
It'd be awesome if a selection could swap quotes with curly quotes.

**Comment by smanolloff** [comment]
What you say seems possible currently and is a matter of configuration. Maybe there is something more to it -- can you provide an example?

**Comment by TeffenEllis** [comment]
Hi @smanolloff,

My usual use-case is editing Markdown and JSON files for [Cloudflare Apps](https://www.cloudflare.com/apps/). We use JSON files with [Schema Form](http://schemaform.io/) to declare the form fields in the apps. These field descriptions often have quotes for properties the user sees:

```json
{
  "properties": {
    "label": {
      "title": "Label",
      "description": "What should this field be tracked as?",
      "placeholder": "“login”, “registration”, “referral website”, etc...",
      "type": "string",
      "order": 2
    }
}
```

I often have to insert these smart quotes manually afterward. Selecting the inner quote contents and making them curly could streamline this up quite a bit 😄 

Cheers

**Comment by smanolloff** [comment]
ah, I see now. This requires support for different start/end quote characters - a feature that is not yet implemented, sorry.

**Comment by colinta** [comment]
I took a look at the code, it would not be easy to have this feature without a major refactor.
