### ISSUE TITLE
Can’t make it work in Sublime Text 3 with a PHP file

### ISSUE THREAD

**Issue by onirix** [colinta/SublimeChangeQuotes#35]
Take a look at this screen capture :
![capture](https://user-images.githubusercontent.com/1549748/33167630-6ce63ff2-d03e-11e7-8029-461e50d52561.gif)

The settings are the default ones.

Thanks for your help

**Comment by onirix** [comment]
Ok I make it work with this User setting :

```
{
	"lists": {
		"default": {
			"quotes": [["'", "\""],["\"", "'"]]
		}
	}
}
```

**Comment by smanolloff** [comment]
👍
